using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using RentalManager.Core.Interfaces;

namespace RentalManager.Infrastructure.Documents;

public sealed class ReceiptService : IReceiptService
{
    public ReceiptService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
        QuestPDF.Settings.CheckIfAllTextGlyphsAreAvailable = true;
    }

    public byte[] CreateReceipt(ReceiptData data) => Document.Create(document => document.Page(page =>
    {
        page.Size(PageSizes.A4);
        page.Margin(40);
        page.DefaultTextStyle(x => x.FontSize(12).FontFamily("Lato", "Noto Sans Thai", "Thonburi"));
        page.Header().Column(column =>
        {
            column.Item().Text("AMP RENTAL").FontSize(22).Bold().FontColor(Colors.Green.Darken2);
            column.Item().Text($"RECEIPT #{data.PaymentId:000000}").FontSize(14).Bold();
        });
        page.Content().PaddingVertical(24).Column(column =>
        {
            column.Spacing(10);
            Row(column, "Room", data.RoomNumber);
            Row(column, "Tenant", data.TenantName);
            Row(column, "Billing period", data.BillingPeriod);
            Row(column, "Paid at (UTC)", data.PaidAtUtc.ToString("yyyy-MM-dd HH:mm:ss"));
            Row(column, "Method", data.Method);
            column.Item().PaddingTop(16).Background(Colors.Grey.Lighten3).Padding(18)
                .Text($"PAID  THB {data.PaidAmount:N2}").FontSize(20).Bold();
        });
        page.Footer().AlignCenter().Text("Generated by Amp Rental Manager").FontSize(9).FontColor(Colors.Grey.Darken1);
    })).GeneratePdf();

    public byte[] CreateSettlementStatement(SettlementStatementData data) => Document.Create(document => document.Page(page =>
    {
        page.Size(PageSizes.A4);
        page.Margin(40);
        page.DefaultTextStyle(x => x.FontSize(11).FontFamily("Lato", "Noto Sans Thai", "Thonburi"));
        page.Header().Text($"MOVE-OUT SETTLEMENT #{data.SettlementId:000000}").FontSize(18).Bold();
        page.Content().PaddingVertical(20).Column(column =>
        {
            column.Spacing(8);
            Row(column, "Room / Tenant", $"{data.RoomNumber} / {data.TenantName}");
            Row(column, "Move-out date", data.MoveOutDate.ToString("yyyy-MM-dd"));
            MoneyRow(column, "Deposit", data.DepositAmount);
            MoneyRow(column, "Final water", -data.FinalWaterAmount);
            MoneyRow(column, "Final electricity", -data.FinalElectricAmount);
            MoneyRow(column, "Outstanding invoices", -data.OutstandingAmount);
            foreach (var deduction in data.Deductions)
            {
                MoneyRow(column, $"Damage: {deduction.Description}", -deduction.Amount);
                if (deduction.Photo is { Length: > 0 })
                    column.Item().MaxHeight(180).Image(deduction.Photo).FitArea();
            }
            if (data.IsForfeited) MoneyRow(column, "Forfeited deposit", -data.ForfeitedAmount);
            column.Item().PaddingTop(12).LineHorizontal(1);
            MoneyRow(column, "Refund to tenant", data.RefundAmount, true);
            MoneyRow(column, "Additional amount due", data.AmountDueFromTenant, true);
        });
        page.Footer().AlignCenter().Text("This statement itemizes every deposit deduction.").FontSize(9);
    })).GeneratePdf();

    private static void Row(ColumnDescriptor column, string label, string value) =>
        column.Item().Row(row =>
        {
            row.RelativeItem().Text(label).FontColor(Colors.Grey.Darken1);
            row.RelativeItem().AlignRight().Text(value);
        });

    private static void MoneyRow(ColumnDescriptor column, string label, decimal amount, bool bold = false) =>
        column.Item().Row(row =>
        {
            var left = row.RelativeItem().Text(label);
            var right = row.RelativeItem().AlignRight().Text($"THB {amount:N2}");
            if (bold) { left.Bold(); right.Bold(); }
        });
}
