// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalManager.Infrastructure.Data;

#nullable disable

namespace RentalManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    [Migration("20260831025504_AddMessagingAndVerification")]
    partial class AddMessagingAndVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalManager.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditId");

                    b.HasIndex("EntityName", "EntityKey", "ChangedAt");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("RentalManager.Core.Entities.BillingPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<byte>("GraceDays")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("LateFeeAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("LateFeeCap")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LateFeeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PolicyId");

                    b.HasIndex("EffectiveFrom")
                        .IsUnique();

                    b.ToTable("BillingPolicy", null, t =>
                        {
                            t.HasCheckConstraint("CK_LateFeeType", "[LateFeeType] IN ('None','PerDay','Flat')");

                            t.HasCheckConstraint("CK_LateFee_NonNegative", "[LateFeeAmount] >= 0 AND ([LateFeeCap] IS NULL OR [LateFeeCap] >= 0)");
                        });

                    b.HasData(
                        new
                        {
                            PolicyId = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            GraceDays = (byte)5,
                            LateFeeAmount = 0m,
                            LateFeeType = "None",
                            Note = "ยังไม่เก็บค่าปรับ ใช้แค่เตือนทางไลน์"
                        });
                });

            modelBuilder.Entity("RentalManager.Core.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("AdjustmentAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("AdjustmentNote")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasColumnType("char(7)");

                    b.Property<short>("DaysCharged")
                        .HasColumnType("smallint");

                    b.Property<byte>("DaysInPeriod")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ElectricAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComputedColumnSql("[ElectricUnits] * [ElectricRate]", true);

                    b.Property<decimal>("ElectricRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ElectricUnits")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsProrated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("CONVERT(bit, CASE WHEN [DaysCharged] <> [DaysInPeriod] THEN 1 ELSE 0 END)", true);

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<decimal>("RentAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComputedColumnSql("[RentAmount] + ([WaterUnits] * [WaterRate]) + ([ElectricUnits] * [ElectricRate]) + [TrashAmount] + [AdjustmentAmount]", true);

                    b.Property<decimal>("TrashAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WaterAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComputedColumnSql("[WaterUnits] * [WaterRate]", true);

                    b.Property<decimal>("WaterRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WaterUnits")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("RoomId", "BillingPeriod", "TenantId")
                        .IsUnique();

                    b.ToTable("Invoice", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invoice_Days", "[DaysCharged] > 0 AND [DaysCharged] <= [DaysInPeriod]");

                            t.HasCheckConstraint("CK_Invoice_Units", "[WaterUnits] >= 0 AND [ElectricUnits] >= 0");
                        });
                });

            modelBuilder.Entity("RentalManager.Core.Entities.MeterReading", b =>
                {
                    b.Property<int>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReadingId"));

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasColumnType("char(7)");

                    b.Property<decimal>("ElectricCurrent")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ElectricPrev")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ElectricUnits")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasComputedColumnSql("[ElectricCurrent] - [ElectricPrev]", true);

                    b.Property<DateOnly>("ReadAt")
                        .HasColumnType("date");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("WaterCurrent")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("WaterPrev")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("WaterUnits")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasComputedColumnSql("[WaterCurrent] - [WaterPrev]", true);

                    b.HasKey("ReadingId");

                    b.HasIndex("RoomId", "BillingPeriod")
                        .IsUnique();

                    b.ToTable("MeterReading", null, t =>
                        {
                            t.HasCheckConstraint("CK_Electric_NotNegative", "[ElectricCurrent] >= [ElectricPrev]");

                            t.HasCheckConstraint("CK_Water_NotNegative", "[WaterCurrent] >= [WaterPrev]");
                        });
                });

            modelBuilder.Entity("RentalManager.Core.Entities.MoveOutSettlement", b =>
                {
                    b.Property<int>("SettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettlementId"));

                    b.Property<decimal>("AmountDueFromTenant")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComputedColumnSql("CASE WHEN ([FinalWaterAmount] + [FinalElectricAmount] + [OutstandingAmount] + [DeductionAmount]) > [DepositAmount] THEN ([FinalWaterAmount] + [FinalElectricAmount] + [OutstandingAmount] + [DeductionAmount]) - [DepositAmount] ELSE 0 END", true);

                    b.Property<decimal>("DeductionAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FinalElectricAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FinalWaterAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ForfeitReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ForfeitedAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComputedColumnSql("CASE WHEN [IsForfeited] = 1 AND [DepositAmount] > ([FinalWaterAmount] + [FinalElectricAmount] + [OutstandingAmount] + [DeductionAmount]) THEN [DepositAmount] - ([FinalWaterAmount] + [FinalElectricAmount] + [OutstandingAmount] + [DeductionAmount]) ELSE 0 END", true);

                    b.Property<bool>("IsForfeited")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthsStayed")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly>("MoveOutDate")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("OutstandingAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("RefundAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComputedColumnSql("CASE WHEN [IsForfeited] = 1 THEN 0 WHEN [DepositAmount] > ([FinalWaterAmount] + [FinalElectricAmount] + [OutstandingAmount] + [DeductionAmount]) THEN [DepositAmount] - ([FinalWaterAmount] + [FinalElectricAmount] + [OutstandingAmount] + [DeductionAmount]) ELSE 0 END", true);

                    b.Property<string>("RefundMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SettledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDeducted")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComputedColumnSql("[FinalWaterAmount] + [FinalElectricAmount] + [OutstandingAmount] + [DeductionAmount]", true);

                    b.HasKey("SettlementId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("MoveOutSettlement", (string)null);
                });

            modelBuilder.Entity("RentalManager.Core.Entities.NotificationLog", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("InvoiceId", "NotificationType")
                        .IsUnique()
                        .HasFilter("[InvoiceId] IS NOT NULL");

                    b.ToTable("NotificationLog", (string)null);
                });

            modelBuilder.Entity("RentalManager.Core.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("SlipHash")
                        .HasColumnType("char(64)");

                    b.Property<string>("SlipImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SlipRef")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VerificationNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("SlipHash")
                        .IsUnique()
                        .HasFilter("[SlipHash] IS NOT NULL");

                    b.HasIndex("SlipRef")
                        .IsUnique()
                        .HasFilter("[SlipRef] IS NOT NULL");

                    b.ToTable("Payment", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Positive", "[PaidAmount] > 0");
                        });
                });

            modelBuilder.Entity("RentalManager.Core.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PayeeCents")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("RoomId");

                    b.HasIndex("PayeeCents")
                        .IsUnique();

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("Room", null, t =>
                        {
                            t.HasCheckConstraint("CK_Room_Rent", "[MonthlyRent] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            IsActive = true,
                            MonthlyRent = 1800m,
                            PayeeCents = 0.01m,
                            RoomNumber = "1"
                        },
                        new
                        {
                            RoomId = 2,
                            IsActive = true,
                            MonthlyRent = 2000m,
                            PayeeCents = 0.02m,
                            RoomNumber = "2"
                        },
                        new
                        {
                            RoomId = 3,
                            IsActive = true,
                            MonthlyRent = 2200m,
                            PayeeCents = 0.03m,
                            RoomNumber = "3"
                        },
                        new
                        {
                            RoomId = 4,
                            IsActive = true,
                            MonthlyRent = 2000m,
                            PayeeCents = 0.04m,
                            RoomNumber = "4"
                        },
                        new
                        {
                            RoomId = 5,
                            IsActive = true,
                            MonthlyRent = 2000m,
                            PayeeCents = 0.05m,
                            RoomNumber = "5"
                        },
                        new
                        {
                            RoomId = 6,
                            IsActive = true,
                            MonthlyRent = 1800m,
                            PayeeCents = 0.06m,
                            RoomNumber = "6"
                        });
                });

            modelBuilder.Entity("RentalManager.Core.Entities.SettlementDeduction", b =>
                {
                    b.Property<int>("DeductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeductionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SettlementId")
                        .HasColumnType("int");

                    b.HasKey("DeductionId");

                    b.HasIndex("SettlementId");

                    b.ToTable("SettlementDeduction", null, t =>
                        {
                            t.HasCheckConstraint("CK_Deduction_Positive", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("RentalManager.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly?>("DepositReceivedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DepositRefundedAt")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LineUserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte>("MinimumStayMonths")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("MovedInAt")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MovedOutAt")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("TenantId");

                    b.HasIndex("LineUserId")
                        .HasFilter("[LineUserId] IS NOT NULL");

                    b.HasIndex("RoomId")
                        .IsUnique()
                        .HasFilter("[MovedOutAt] IS NULL");

                    b.ToTable("Tenant", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tenant_Deposit", "[DepositAmount] >= 0");
                        });
                });

            modelBuilder.Entity("RentalManager.Core.Entities.TenantLinkCode", b =>
                {
                    b.Property<int>("LinkCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkCodeId"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LinkCodeId");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("TenantLinkCode", (string)null);
                });

            modelBuilder.Entity("RentalManager.Core.Entities.UtilityRate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateId"));

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<decimal>("ElectricPerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TrashPerMonth")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WaterPerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("RateId");

                    b.HasIndex("EffectiveFrom")
                        .IsUnique();

                    b.ToTable("UtilityRate", null, t =>
                        {
                            t.HasCheckConstraint("CK_UtilityRate_NonNegative", "[WaterPerUnit] >= 0 AND [ElectricPerUnit] >= 0 AND [TrashPerMonth] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            RateId = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            ElectricPerUnit = 12m,
                            Note = "อัตราเริ่มต้น",
                            TrashPerMonth = 40m,
                            WaterPerUnit = 20m
                        });
                });

            modelBuilder.Entity("RentalManager.Core.Entities.Invoice", b =>
                {
                    b.HasOne("RentalManager.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalManager.Core.Entities.Tenant", "Tenant")
                        .WithMany("Invoices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentalManager.Core.Entities.MeterReading", b =>
                {
                    b.HasOne("RentalManager.Core.Entities.Room", "Room")
                        .WithMany("MeterReadings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RentalManager.Core.Entities.MoveOutSettlement", b =>
                {
                    b.HasOne("RentalManager.Core.Entities.Tenant", "Tenant")
                        .WithOne()
                        .HasForeignKey("RentalManager.Core.Entities.MoveOutSettlement", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentalManager.Core.Entities.NotificationLog", b =>
                {
                    b.HasOne("RentalManager.Core.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalManager.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentalManager.Core.Entities.Payment", b =>
                {
                    b.HasOne("RentalManager.Core.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("RentalManager.Core.Entities.SettlementDeduction", b =>
                {
                    b.HasOne("RentalManager.Core.Entities.MoveOutSettlement", "Settlement")
                        .WithMany("Deductions")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("RentalManager.Core.Entities.Tenant", b =>
                {
                    b.HasOne("RentalManager.Core.Entities.Room", "Room")
                        .WithMany("Tenants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RentalManager.Core.Entities.TenantLinkCode", b =>
                {
                    b.HasOne("RentalManager.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentalManager.Core.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RentalManager.Core.Entities.MoveOutSettlement", b =>
                {
                    b.Navigation("Deductions");
                });

            modelBuilder.Entity("RentalManager.Core.Entities.Room", b =>
                {
                    b.Navigation("MeterReadings");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("RentalManager.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
